name: Teste Runner Local

on:
  push:
    branches:
      - main

jobs:
  teste:
    runs-on: self-hosted

    steps:
      - name: Informacoes da VM
        run: |
          echo "Hostname:"
          hostname

          echo "Usuario:"
          whoami

          echo "Diretorio:"
          pwd
