name: Instalar Zabbix

on:
  push:
    branches:
      - main

jobs:
  instalar:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Zabbix
        run: |
          chmod +x scripts/install_zabbix.sh
          ./scripts/install_zabbix.sh
